### PR TITLE
Add NRF52SPI and NRF52840 build fixes

### PR DESCRIPTION
**Pull request by mmoskal**
Depends on https://github.com/lancaster-university/codal-core/pull/27

### CODE REVIEW

**Comment by ladyada** [comment]
... does this mean nrf52840 may be supported :)

**Comment by jamesadevine** [comment]
It definitely works on a NRF52-DK :wink:

**Comment by ladyada** [comment]
nice - have you tried out this fancy round board? https://www.adafruit.com/product/4333

**Comment by jamesadevine** [comment]
Oh! That looks like an exciting little board...

We may be receiving some shortly... :smile:

**Comment by finneyj** [comment]
Yep... nice board that... ;)

p.s. Thanks for hosting Lorraine and Rachel last week @ladyada - much appreciated. I know Lorraine especially appreciated her time with you.

**Comment by Teknikio** [comment]
Nice! we have been developing a very similar product over the past year and support would be awesome

https://www.teknikio.com/pages/bluebird

**Comment by ladyada** [comment]
@Teknikio hiya if its an nrf52840 you can easily add circuitpython support

**Comment by Teknikio** [comment]
@ladyada Awesome we will check that out, would love to share our software with you too when it's ready

**Pull request merged**
