### PR TITLE
use same packet size as microbit to match CRC

### PR DESCRIPTION
**Pull request by pelikhan**
Required to have a nrf52 talk to micro:bit.

### CODE REVIEW

**Comment by jamesadevine** [comment]
I'm happy to merge if the reason is alignment with the micro:bit interface. 

I would have thought that the maximum packet size would have no bearing on the calculation of the CRC. It should only calculate up to and including LENGTH bytes.

**Comment by pelikhan** [comment]
32 is part of the “spec” by now.

**Comment by jamesadevine** [comment]
Yup agree, but it seems like you're also reporting a bug? Are you saying the radios are incompatible with different max packet sizes?

**Comment by pelikhan** [comment]
Be happy and merge

**Comment by jamesadevine** [comment]
Hahaha :smile:

**Comment by pelikhan** [comment]
They are incompatible with different sizes. Regardless if we have some bug, the Nrf51 would not be able to read 40bytes packets.

**Pull request merged**
