### PR TITLE
Fix incorrect mapping for BitMode32

### LINKED ISSUE #22: Error in clock config
I think NRFLowLevelTimer.cpp's `setBitMode()` has an error.  It looks like `BitMode32` is using the wrong constant.  

According to the NRF52 docs it should be 3.  See: https://infocenter.nordicsemi.com/topic/ps_nrf52833/timer.html?cp=4_1_0_5_27_4_11#register.BITMODE

See: https://github.com/lancaster-university/codal-nrf52/blob/86be5f29342b2bac245d42ad26f81a4e7fde2c69/source/NRFLowLevelTimer.cpp#L232

### PR DESCRIPTION
**Pull request by jamesadevine**
Fixes #22.

I've checked NRF52832, NRF52833, NRF52840 datasheets, and this change should correctly apply to all of them. A quick verification would be nice @bsiever?

Thanks for the heads up :smile:

### CODE REVIEW

**Comment by bsiever** [comment]
Looks good. I've done some testing on a Microbit V2 with the updated value (`BITMODE=3`) and it works as I would expect.  Thanks!

**Comment by finneyj** [comment]
Thanks @jamesadevine  @bsiever 

james - quick sanity check before we commit... is anything in the codebase using the old (incorrect) version of this constant? if so, we should schedule some tests on that code to make sure we don't break something.

**Comment by jamesadevine** [comment]
Don't think so. A quick search against the lancs org doesn't turn up anything significant. The only usage with respect to the NRF is in NRFLowLevelTimer itself:

https://github.com/search?q=org%3Alancaster-university+setBitMode&type=code

Just to be clear, we aren't changing the value of the constant, we are changing the value the constant maps to, and therefore the value that is placed in the hardware register.

**Comment by finneyj** [comment]
Thanks @jamesadevine 

That's precisely what I was worried about...  :)

The default mode has always been 32-bit: https://github.com/lancaster-university/codal-nrf52/blob/3ec21bd3278f8743f05b9ed7ce34ae6b4fbc71b3/source/NRFLowLevelTimer.cpp#L89

But, because the underlying hardware constant was incorrect before this patch, all the timers would actually have been running in 24-bit mode, right? After the patch, they will actually be running at 32 bit. This means we will see different behaviour w.r.t. overflow etc on any existing drivers... 

We should definitely apply this patch, but i think we should also run tests on any timer dependent code before releasing next tag...

**Comment by jamesadevine** [comment]
Yes, agreed the timers will have been running in 24-bit mode, though overflow conditions would have been written under the assumption the timer in 32-bit . Overflow condition checks would have been ineffective regardless :smile: I can see your point if you are worried about the code working correctly though 😁 

The NRFLowLevel timer class is used here:

https://github.com/search?q=org%3Alancaster-university+NRFLowLeveltimer&type=code

The abstract driver model is used here:

https://github.com/search?q=org%3Alancaster-university+LowLeveltimer&type=code

**Comment by mmoskal** [comment]
The Timer::sync() is only using low 16 bits of the timer. Our impl of timers on STM32 only supports 16 bit.

The interesting bit is this
```
    timer.setCompare(this->ccEventChannel, timer.captureCounter() + t);
```
in Timer.cpp - I guess if you set the timer to 24 bit it's only going to compare the low 24 bits, so it works.

**Comment by bsiever** [comment]
It works now as long as updates happen frequently enough.  With the 32-bit timer it's possible to have ~18 minutes of gap between `sync()` (vs. 16s with 24-bits and 6ms with just 16 bits).  Of course, if it's still cast to 16 bits in `Timer` it probably doesn't matter.

**Comment by mmoskal** [comment]
The scheduler tick is typically around 5ms. BTW, the Timer works with 65ms on 16bit, not 6ms, so we are safe here.

**Comment by finneyj** [comment]
Thanks for all the due diligence folks. Agree risks are low.

The NRF52LowLevelTimer is also used by some other drivers directly (ADC, LED matrix drivers etc), so I'll do a quick sanity check of those before next release.

**Pull request merged**
